#!/usr/bin/env bash
# Compile the application channels from the memory sources. Idempotent; run
# after every promote (Mode 2) and whenever Setup detects drift.
#
# Sources (in ~/.claude/learning-loop-memory/):
#   preferences.md            universal taste (imported by CLAUDE.md directly)
#   preferences-<stack>.md    stack-scoped rules, carrying their own `paths:`
#                             frontmatter (e.g. preferences-go-backend.md)
#   examples.md               exemplar pointers (imported by CLAUDE.md directly)
#
# Compiled artifacts:
#   ~/.claude/rules/learning-loop-<stack>.md   verbatim copy of each stack file;
#       Claude Code loads it only when touching files matching its `paths:`
#   ~/.claude/AGENTS.md                        a marker-delimited block with the
#       full memory content, so Codex gets the rules inline instead of being
#       asked to go read files (advisory pointers get skipped mid-task)
set -euo pipefail

M="$HOME/.claude/learning-loop-memory"
R="$HOME/.claude/rules"
A="$HOME/.claude/AGENTS.md"
BEGIN='<!-- learning-loop:compiled — generated by compile-channels.sh; edit sources in ~/.claude/learning-loop-memory/ -->'
END='<!-- /learning-loop:compiled -->'

mkdir -p "$R"

# 1. stack files -> path-scoped rules (verbatim; the source carries frontmatter)
for SRC in "$M"/preferences-*.md; do
  [ -f "$SRC" ] || continue
  STACK="$(basename "$SRC" .md)"; STACK="${STACK#preferences-}"
  cp "$SRC" "$R/learning-loop-$STACK.md"
done

# 2. AGENTS.md compiled block (replace between markers, or append)
TMP="$(mktemp)"
{
  echo "$BEGIN"
  echo
  cat "$M/preferences.md"
  for SRC in "$M"/preferences-*.md; do
    [ -f "$SRC" ] || continue
    echo
    # strip YAML frontmatter — path scoping is meaningless to Codex
    awk 'NR==1 && $0=="---" {fm=1; next} fm && $0=="---" {fm=0; next} !fm' "$SRC"
  done
  echo
  cat "$M/examples.md"
  echo "$END"
} > "$TMP"

if [ -f "$A" ] && grep -qF 'learning-loop:compiled' "$A"; then
  awk -v repl="$TMP" '
    /<!-- learning-loop:compiled/ {skip=1; while ((getline line < repl) > 0) print line; next}
    /<!-- \/learning-loop:compiled -->/ {skip=0; next}
    !skip' "$A" > "$A.tmp" && mv "$A.tmp" "$A"
else
  { [ -f "$A" ] && cat "$A"; echo; cat "$TMP"; } > "$A.tmp" && mv "$A.tmp" "$A"
fi
rm -f "$TMP"
echo "compiled: $(ls "$R"/learning-loop-*.md 2>/dev/null | wc -l) rules file(s), AGENTS.md block refreshed"
